export default {
  Source: [
    'Timestamp',
    'Date of post',
    'Source Url',
    'Embed links',
    'Google Drive Link',
    'Post caption',
    'Possible location name',
    'Possible address',
    'Possible lat, lng',
    'Type',
    'Manual location',
    'Manual lat, lng',
    'Map link',
    'Archive link',
    'Description',
    'Comment',
  ],
  Events: [
    'Id',
    'Description',
    'Date',
    'Time',
    'Site Key',
    'Lat Lng',
    'Incident Types',
    'Means of Attack',
    'Sources',
    'Include in map',
  ],
  Sites: ['Site Key', 'Town', 'Oblast', 'Lat Lng'],
  Categories: [],
  Associations: ['Id', 'Description', 'Mode', 'Filter Path'],
  EXPORT_EVENTS: [
    'id',
    'description',
    'date',
    'time',
    'location',
    'latitude',
    'longitude',
    'association1',
    'association2',
    'source1',
  ],
  EXPORT_SOURCES: [
    'id',
    'title',
    'thumbnail',
    'description',
    'type',
    'path1',
    'path2',
    'path3',
  ],
  EXPORT_ASSOCIATIONS: [
    'id',
    'title',
    'desc',
    'mode',
    'filter_path0',
    'filter_path1',
    'filter_path2',
    'filter_path3',
  ],
};
