export const oblastOptions = [
  { label: 'Cherkasy Oblast', value: 'CHERKASY' },
  { label: 'Chernihiv Oblast', value: 'CHERNIHIV' },
  { label: 'Chernivtsi Oblast', value: 'CHERNIVTSI' },
  { label: 'Dnipropetrovsk Oblast', value: 'DNIPROPETROVSK' },
  { label: 'Donetsk Oblast', value: 'DONETSK' },
  { label: 'Ivano-Frankivsk Oblast', value: 'IVANO-FRANKIVSK' },
  { label: 'Kharkiv Oblast', value: 'KHARKVIV' },
  { label: 'Kherson Oblast', value: 'KHERSON' },
  { label: 'Khmelnytskyi Oblast', value: 'KHMELNYTSKYI' },
  { label: 'Kyiv Oblast', value: 'KYIV' },
  { label: 'Kirovohrad Oblast', value: 'KIROVOHRAD' },
  { label: 'Luhansk Oblast', value: 'LUHANSK' },
  { label: 'Lviv Oblast', value: 'LVIV' },
  { label: 'Mykolaiv Oblast', value: 'MYKOLAIV' },
  { label: 'Odessa Oblast', value: 'ODESSA' },
  { label: 'Poltava Oblast', value: 'POLTAVA' },
  { label: 'Rivne Oblast', value: 'RIVNE' },
  { label: 'Sumy Oblast', value: 'SUMY' },
  { label: 'Ternopil Oblast', value: 'TERNOPIL' },
  { label: 'Vinnytsia Oblast', value: 'VINNYTSIA' },
  { label: 'Volyn Oblast', value: 'VOLYN' },
  { label: 'Zakarpattia Oblast', value: 'ZAKARPATTIA' },
  { label: 'Zaporizhzhia Oblast', value: 'ZAPORIZHZHIA' },
  { label: 'Zhytomyr Oblast', value: 'ZHYTOMYR' }
]
